import React, { useState, useEffect } from 'react'
import Head from 'next/head'
import { motion } from "framer-motion"
import { useRouter } from 'next/router';
import MainLayout from '@/components/layout/MainLayout'
import { NEWSWIRE_ITEMS } from '@/utils/constants'
import NewswireArticleDetails from '@/components/newswire/NewswireArticleDetails';


type Props = {

}


export default function NewswireArticle({ }: Props) {
    const router = useRouter();
    const [collection, setCollection] = useState<any>(null);

    useEffect(() => {
        const { article: collectionName } = router.query;
        if (collectionName) {
            const sanitizedCollectionName = collectionName
                .toString()
                .replace(/-/g, ' ')
                .replace(/(^|\s)\S/g, (match) => match.toUpperCase());

            const collectionItem = NEWSWIRE_ITEMS.find(
                (item) => item.title.toLowerCase() === sanitizedCollectionName.toLowerCase()
            );

            setCollection(collectionItem || null);
        }
    }, [router.query])
    return (
        <>
            {collection ? (
                <motion.div
                    initial={{ opacity: 0 }}
                    whileInView={{ opacity: 1 }}
                    viewport={{ once: true }}
                    className="  dark:text-gray-400 scrollbar-hide max-h-screen max-w-screen overflow-auto"
                >
                    <Head>
                        <title>{collection.title}| Dave&apos;s Rockstar Games Rebuild </title>
                        <meta name="description" content="Generated by create next app" />
                        <meta name="viewport" content="width=device-width, initial-scale=1" />
                        <link rel="icon" href="/favicon.ico" />
                    </Head>
                    <main className=''>
                        <MainLayout title='Newswire'>
                            <NewswireArticleDetails collection={collection}/>
                        </MainLayout>
                    </main>
                </motion.div>
            ) : (
                <motion.div
                    initial={{ opacity: 0 }}
                    whileInView={{ opacity: 1 }}
                    viewport={{ once: true }}
                    className="  dark:text-gray-400 scrollbar-hide max-h-screen max-w-screen overflow-auto"
                >
                    <Head>
                        <title>Dave&apos;s Rockstar Games Rebuild | Newswire </title>
                        <meta name="description" content="Generated by create next app" />
                        <meta name="viewport" content="width=device-width, initial-scale=1" />
                        <link rel="icon" href="/favicon.ico" />
                    </Head>
                    <main className=''>
                        <MainLayout title='Newswire'>
                            <div className="h-screen w-screen flex justify-center items-center">Loading...</div>
                        </MainLayout>
                    </main>
                </motion.div>

            )}
        </>
    )
}