import Head from 'next/head'
import { motion } from "framer-motion"
import MainLayout from '@/components/layout/MainLayout'
import HeroSection from '@/components/ui/HeroSection'
import Newswire from '@/components/ui/Newswire'
import FeaturedGamesSection from '@/components/FeaturedGamesSection'

export default function Home() {
  return (
    <motion.div
      initial={{ opacity: 0 }}
      whileInView={{ opacity: 1 }}
      viewport={{ once: true }}
      className="bg-transparent  dark:text-gray-400 scrollbar-hide max-h-screen max-w-screen overflow-auto"
    >
      <Head>
        <title>Dave&apos;s Rockstar Games Rebuild | Home </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=''>
        <MainLayout title='Home'>
            <HeroSection/>
            <Newswire/>
            <FeaturedGamesSection title="Featured Games" />
        </MainLayout>
      </main>
    </motion.div>
  )
}
